// Mock Data
export const mockEvents = [

  {
      id: 1,
      title: "Community BBQ",
      date: new Date("2025-09-20T17:00:00.000Z").toISOString(),
      location: "Church Lawn",
      description: "Join us for a fun evening of food, games, and fellowship.",
      imageUrl: "https://www.thedailymeal.com/img/gallery/get-grilling-with-the-daily-meal/Ultimate_Grilling_Guide_The_Daily_Meal-min.jpg",
      category: "community",
      time: "5:00 PM",
      speaker: "John Doe",
    },
    {
      id: 2,
      title: "Youth Movie Night",
      date: new Date("2025-09-26T19:00:00.000Z").toISOString(),
      location: "Youth Hall",
      description: "A fun movie night for all our youth group members.",
      imageUrl: "https://static.vecteezy.com/system/resources/thumbnails/057/280/960/small_2x/a-cozy-scene-featuring-popcorn-and-drinks-ideal-for-movie-night-photo.jpg",
      category: "youth",
      time: "7:00 PM",
    },
    {
      id: 3,
      title: "Worship Night",
      date: new Date("2025-10-04T18:30:00.000Z").toISOString(),
      location: "Main Sanctuary",
      description: "An evening of worship and prayer.",
      imageUrl: "https://t4.ftcdn.net/jpg/06/09/03/19/360_F_609031999_gAZEzpdJHrVZtOpONPwWgd85Y1IY6I3b.jpg",
      category: "service",
      time: "6:30 PM",
      speaker: "Worship Team",
    },
    {
      id: 4,
      title: "Men's Breakfast",
      date: new Date("2025-08-16T08:00:00.000Z").toISOString(),
      location: "Fellowship Hall",
      description: "A time for men to connect and grow together.",
      imageUrl: "https://www.shutterstock.com/image-photo/food-eating-family-concept-group-260nw-794156569.jpg",
      category: "community",
      time: "8:00 AM",
      speaker: "Guest Speaker",
    },
];

export const mockSermons = [
  { id: '1', 
    title: 'The Power of Forgiveness', 
    speaker: 'Pastor John Doe', 
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), 
    description: 'An inspiring message on the freedom found in forgiveness.', 
    videoUrl: '#', audioUrl: '#', 
    thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=225', 
    scripture: 'Ephesians 4:32', 
    series: 'Foundations' },
  { id: '2', 
    title: 'Living with Purpose', 
    speaker: 'Pastor Jane Smith', 
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), 
    description: 'Discover how to live a life full of meaning and purpose.', 
    videoUrl: '#', 
    thumbnailUrl: 'https://t3.ftcdn.net/jpg/07/32/29/00/360_F_732290082_mnqux9pnrVIELlvnHbeVEhUSTge5fDs3.jpg', 
    scripture: 'Jeremiah 29:11' },
  { id: '3', 
    title: 'Hope in Hard Times', 
    speaker: 'Pastor John Doe', 
    date: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(), 
    description: 'Finding strength and hope in God during life\'s challenges.',
    audioUrl: '#', 
    thumbnailUrl: 'https://images.unsplash.com/photo-1593104547489-5cfb3839a3b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=225', 
    scripture: 'Romans 15:13', 
    series: 'Foundations'
  },
  { id: '4', 
    title: 'The Heart of Worship', 
    speaker: 'Pastor Mike Brown', 
    date: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(), 
    description: 'A deep dive into what it means to worship God in spirit and truth.',
    videoUrl: '#', audioUrl: '#', 
    thumbnailUrl: 'https://www.pptxworship.com/wp-content/uploads/2019/02/Heart-of-Worship-%E2%80%93-Matt-Redman.jpg', 
    scripture: 'John 4:24'
  },
];
